# Whisker analysis configuration
# This configuration file contains parameters for whisker-specific behavioral analysis

mode: classification

# Analysis parameters
analysis_params:
  optimize: false  # Whether to run hyperparameter optimization
  use_smote: false  # Whether to use SMOTE for handling class imbalance
  n_trials: 500  # Number of optimization trials
  file_prefix: whisker_all_contexts

# Feature columns for whisker analysis
whisker_features:
  - context
  - subject
  - cum_water
  - prev_trial_correct
  # - trial_number
  # - context_block_index
  - trial_in_block
  - whisker_trial_in_block
  - prev_trial_water
  - last_stimulus_type
  - prev_whisker_rewarded
  - time_since_last_stimulus
  - lick_flag 

feature_labels:
  - Context
  - Mouse ID
  - Cumulative water
  - Previous trial correct
  - Trial in block
  - Whisker trial in block
  - Previous trial water
  - Last stimulus type
  - Previous whisker rewarded
  - Time since last stimulus
  - Lick flag

outcome_column: Lick flag

# Categorical columns for analysis
categorical_columns:
  - Context
  - Mouse ID
  - Previous trial correct
  - Previous whisker rewarded
  - Last stimulus type

# Feature interactions to analyze
interaction_features:
  # - [context, whisker_trial_in_block]
  # - [whisker_trial_in_block, context]
  - [Context, Whisker trial in block]
  - [Whisker trial in block, Context]


