# Whisker analysis configuration
# This configuration file contains parameters for whisker-specific behavioral analysis

mode: classification
leave_out_one_session: true  # Leave out one session for testing


# Analysis parameters
analysis_params:
  optimize: true  # Whether to run hyperparameter optimization
  use_smote: false  # Whether to use SMOTE for handling class imbalance
  n_trials: 400  # Number of optimization trials
  file_prefix: whisker_all_contexts

# Feature columns for whisker analysis
whisker_features:
  - context
  - subject
  - cum_water
  - prev_trial_correct
  # - trial_number
  # - context_block_index
  # - trial_in_block
  - whisker_trial_in_block
  # - time_in_context
  - prev_trial_water
  - last_stimulus_type
  - prev_whisker_rewarded
  - time_since_last_stimulus
  - BaselineMotionEnergy
  - session
  - lick_flag 

feature_labels:
  - Context
  - Mouse ID
  - Cumulative water
  - Previous trial correct
  # - Trial in block
  - Whisker trial in block
  # - Time since transition
  - Previous trial water
  - Last stimulus type
  - Previous whisker rewarded
  - Time since last stimulus
  - Baseline motion energy
  - Session ID
  - Lick flag

outcome_column: Lick flag

# Categorical columns for analysis
categorical_columns:
  - Context
  - Mouse ID
  - Previous trial correct
  - Previous whisker rewarded
  - Last stimulus type
  - Session ID

# Feature interactions to analyze
interaction_features_discrete:
  # - [context, whisker_trial_in_block]
  # - [whisker_trial_in_block, context]
  # - [Context, Whisker trial in block]
  - [Whisker trial in block, Context]
  # - [Context, Baseline motion energy]
  # - [Trial in block, Context]
  # - [Time since transition, Context]
  # - ['Previous trial water, Context']
  # - ['Previous trial water, Trial in block']
  # - [Previous trial water, Time since transition]
  # - [Trial in block, Whisker trial in block]
  # - [Whisker trial in block, Trial in block]

# interaction_features_continuous:
#   - [Time since transition, Context]
